"""
Django settings for museRental project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%y^j#fc7fd3d0!b(0j$g@bs7nf5y#+eps$!mv91-jz#zg5^!ss'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Application definition

INSTALLED_APPS = [
    'main',
    'accounts',
    'explore',
    'event',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'user_visit',
    'crispy_forms',
    'leaflet_point',
]
CRISPY_TEMPLATE_PACK = 'bootstrap5'

LEAFLET_POINT_CONFIG = {
    'map_height': 500,
    'tile_layer': 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    'attribution': '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    'initial_lat': 	27.700769,
    'initial_lng': 85.300140,
    'initial_zoom': 10,
    'geocoder':True,
    'style': 'width: 500px;'
}

# CKeditor Config
CKEDITOR_CONFIGS = {
    'default': {
        'width': '100%',
        'tabSpaces': 4,

    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # for uservisit
    'user_visit.middleware.UserVisitMiddleware',
]

CSRF_TRUSTED_ORIGINS = ['https://samirchaulagain.com.np']

ROOT_URLCONF = 'museRental.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [os.path.join(BASE_DIR,'template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'museRental.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# settings.py

# Define the directory where your static files are located.
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.User'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465  # SMTP server port (587 for TLS)
EMAIL_USE_SSL = True
# EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'muserentalhub@gmail.com'
EMAIL_HOST_PASSWORD = 'q w q w p e x z f q e r j d x v'
DEFAULT_FROM_EMAIL = "muserentalhub@gmail.com"
ALLOWED_HOSTS = ['*']

# Optionally, you can set the default 'from' address for outgoing emails
DEFAULT_FROM_EMAIL = 'muserentalhub@gmail.com'

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Muserental Hub Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Muserental Hub",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Muserental Hub",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "/img/Main/logo.png",
      # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,
    "custom_css": "/jazzmin/admin.css",
    "custom_js": None,

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Muserental Hub",

    "login_logo_dark": None,

    # Copyright on the footer
    "copyright": "Muserental Hub",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string 
    "search_model": ["explore.Item"],

   

        ############
    # User Menu #
    ############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/Samir-Chaulagain/MuseRentalHub", "new_window": True, "icon":"fas fa-phone",},
        
    ],
     # Whether to display the side menu
    "show_sidebar": True,
     
    # Whether to aut expand the menu
    "navigation_expanded": True,
# Hide these apps when generating side menu e.g (auth)
    "hide_apps": ["auth.Groups"],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["event.Category", "event.Event", "event.Booking"],

    "icons": {
        "auth": "fas fa-users-cog",
        "accounts.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "event.Category":"fas fa-th-large",
        "event.Event":"fas fa-dungeon",
        "event.Booking": "far fa-calendar",
        "explore.Category":"fas fa-th-large",
        "explore.Item":"fas fa-warehouse",
        "explore.Customer":"fas fa-male",
        "explore.saved_item":"fas fa-save",
        "event.saved_event":"fas fa-save",
        "explore.Image":"fas fa-save",
        "explore.Review":"fab fa-usps",
        "main.Post":"fab fa-usps",
        "User visits":"fab fa-usps",
       
    },
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    
    
    }

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-lightblue",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "slate",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

