# Generated by Django 4.2.6 on 2023-11-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
