# Generated by Django 4.2.7 on 2023-12-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='images/default_image.png', null=True, upload_to='images'),
        ),
    ]
