# Generated by Django 4.2.7 on 2024-01-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
