# Generated by Django 4.2.7 on 2024-01-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('citizenship', 'Citizenship'), ('license', 'License'), ('passport', 'Passport'), ('others', 'Others')], default='citizenship', max_length=20),
        ),
    ]
