# Generated by Django 5.0.2 on 2024-02-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document_type',
            field=models.CharField(choices=[('Citizenship', 'Citizenship'), ('License', 'License'), ('Passport', 'Passport'), ('Others', 'Others')], default='citizenship', max_length=20),
        ),
    ]
