# Generated by Django 5.0.2 on 2024-02-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userloginhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginHistory',
        ),
    ]
