# Generated by Django 5.0.2 on 2024-02-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_remove_event_location_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Default', max_length=300),
        ),
    ]
