# Generated by Django 5.0.2 on 2024-02-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
