# Generated by Django 5.0.2 on 2024-02-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_event_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_available',
            field=models.BooleanField(),
        ),
    ]
