# Generated by Django 5.0.2 on 2024-02-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_rename_is_available_event_is_unavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
