# Generated by Django 4.2.6 on 2023-11-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_price',
            field=models.FloatField(blank=True, default='500'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
