# Generated by Django 4.2.7 on 2024-01-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_event_status_event_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_completed',
        ),
    ]
