# Generated by Django 4.2.7 on 2024-01-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_completed',
        ),
    ]
