# Generated by Django 4.2.6 on 2023-11-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_remove_item_image_remove_item_is_sold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentinstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rentinstrument_Date_of_Booking', models.DateField(blank=True, null=True)),
                ('Rentinstrument_Date_of_Return', models.DateField(blank=True, null=True)),
                ('Total_days', models.IntegerField()),
                ('Advance_amount', models.IntegerField(blank=True, null=True)),
                ('Rentinstrument_Total_amount', models.IntegerField(blank=True, null=True)),
                ('isAvailable', models.BooleanField(default=True)),
                ('customer_email', models.CharField(max_length=100)),
                ('request_responded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('request_status', models.CharField(default='Pending', max_length=30)),
            ],
        ),
    ]
