# Generated by Django 5.0.2 on 2024-02-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_customer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
