# Generated by Django 4.2.6 on 2023-11-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_rentinstrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
