# Generated by Django 5.0.2 on 2024-02-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_customer_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='invoice',
            new_name='invoice_number',
        ),
    ]
