# Generated by Django 4.2.6 on 2023-11-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_rename_is_sold_item_is_closed_item_is_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_closed',
            new_name='is_sold',
        ),
    ]
