# Generated by Django 4.2.7 on 2023-11-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0010_rename_timestamp_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Advance_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Rentitem_Date_of_Booking',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Rentitem_Date_of_Return',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Rentitem_Total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='request_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.DeleteModel(
            name='Rentitem',
        ),
    ]
