# Generated by Django 4.2.7 on 2023-11-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0011_customer_advance_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
    ]
