# Generated by Django 4.2.7 on 2023-11-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0014_alter_item_instrument_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
    ]
