# Generated by Django 4.2.7 on 2024-01-18 18:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explore', '0016_rename_is_closed_item_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_sellable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='instrument_image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='instrument_image2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='instrument_image3',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='applieditems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
