# Generated by Django 4.2.7 on 2024-01-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0020_remove_item_instrument_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sellable',
        ),
    ]
