# Generated by Django 4.2.7 on 2024-01-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0022_alter_item_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Advance_amount',
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='Thimi', max_length=55),
        ),
    ]
