# Generated by Django 5.0.2 on 2024-02-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0029_review_is_rated_alter_review_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_rated',
        ),
    ]
