# Generated by Django 4.2.6 on 2023-11-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='item',
            name='instrument_brand',
            field=models.CharField(default='Default Brand Name', max_length=60),
        ),
        migrations.AddField(
            model_name='item',
            name='instrument_image1',
            field=models.ImageField(default='img/inst1/', upload_to='img/instrument_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='instrument_image2',
            field=models.ImageField(default='img/inst1/', upload_to='img/instrument_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='instrument_image3',
            field=models.ImageField(default='img/inst1/', upload_to='img/instrument_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='instrument_model',
            field=models.CharField(default='Default model Name', max_length=60),
        ),
    ]
