# Generated by Django 4.2.6 on 2023-11-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_rename_is_closed_item_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
