# Generated by Django 4.2.7 on 2023-11-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0015_remove_item_is_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_closed',
            new_name='is_sold',
        ),
    ]
