# Generated by Django 4.2.7 on 2024-01-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0018_remove_item_instrument_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='instrument_image1',
            field=models.ImageField(default='images/default_image1.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='instrument_image2',
            field=models.ImageField(default='images/default_image1.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='instrument_image3',
            field=models.ImageField(default='images/default_image1.jpg', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='itemImage',
        ),
    ]
