# Generated by Django 4.2.7 on 2024-01-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0021_remove_item_is_sellable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('1', 'Solo'), ('2', 'Package'), ('3', 'Sound Accessories')], default=False, max_length=1),
        ),
    ]
