# Generated by Django 4.2.7 on 2024-01-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0023_remove_customer_advance_amount_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
