# Generated by Django 4.2.7 on 2024-01-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_document_photo_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_type',
            field=models.CharField(blank=True, choices=[('citizenship', 'Citizenship'), ('license', 'License'), ('passport', 'Passport'), ('others', 'Others')], max_length=20, null=True),
        ),
    ]
